apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dremio-appset
spec:
  generators:
  - list:
      elements:
      - cluster: docker-k8s
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'dremio-{{cluster}}'
    spec:
      project: local-project
      source:
        repoURL: https://github.com/carlos-ffs/confluent-dremio-fluentbit-logs.git
        targetRevision: HEAD
        path: charts/dremio
        helm:
          releaseName: dremio
          valueFiles: 
          - values.yaml
      destination:
        server: '{{url}}'
        namespace: dremio
      syncPolicy:
        automated:
          prune: true  # Automatically delete resources that no longer exist in Git
          selfHeal: true  # Automatically sync if drift is detected
          allowEmpty: true  # Allows deleting all resources when they are no longer in Git
        syncOptions:
        - CreateNamespace=true
        - RespectIgnoreDifferences=true
        - ServerSideApply=true
      ignoreDifferences:
      # We ignore the license secret so we can manage it outside of GitOps.
      # ArgoCD will create the secret on the first sync, and then ignore any changes.
      # If you don't want to manually manage the secret (like scripts/run.sh does), 
      # you can take advantage of external-secrets to manage the secret for you. 
      # I advise to use spec.target.creationPolicy: 'Merge' in the external-secret CR.
      # With Merge set the external-secret operator does not create a secret. Instead, 
      # it expects the secret to already exist and does not create the secret, but merges in the data fields to the secret.
      # Creation policy details: https://external-secrets.io/main/guides/ownership-deletion-policy/#creation-policy
      # Check example here: https://external-secrets.io/main/api/externalsecret/#example
      - kind: Secret
        name: dremio-license
        namespace: dremio
        jsonPointers:
        - /data
        - /stringData
      - kind: Secret
        name: dremio-mongodb-app-users
        namespace: dremio
        jsonPointers:
        - /data
        - /stringData
      - group: psmdb.dremio.com
        kind: PerconaServerMongoDB
        jqPathExpressions:
        - .spec.replsets[].sidecars[]
      - group: batch
        kind: Job
        name: minio-wait-for-job
        namespace: dremio
      - group: batch
        kind: Job
        name: dremio-cluster-id
        namespace: dremio
      - group: apps
        kind: StatefulSet
        jqPathExpressions:
          - .spec.volumeClaimTemplates[].apiVersion
          - .spec.volumeClaimTemplates[].kind