apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://github.com/carlos-ffs/confluent-dremio-fluentbit-logs.git
  username: <username>
  password: <token>
