apiVersion: v1
kind: Secret
metadata:
  name: dremio-pull-secret
data:
  .dockerconfigjson: <YOUR_BASE64_ENCODED_DOCKER_CONFIG_JSON>
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: dremio-license
type: Opaque
stringData:
  license: <YOUR_DREMIO_LICENSE_KEY>